export const initState = {
    currency: "$",
    currencyObject: "",
    languge: "rus",
    page: "rent",
    pageParam: "",
    fullDataBase: "",
    chosenObject: "",
    sorterValue: "sort",
    searchInput: {
      globalSearchInput:"",
      inputCity:"",
      inputDistrict:"",
      minPrice:-Infinity,
      maxPrice:+Infinity,
      minSqure:-Infinity,
      maxSqure:+Infinity,
      '1+1':false,
      '2+1':false,
      '3+1':false,
      heatingNo:"",
      heatingGas:"",
      heatingElectro:"",
      airYes:true,
      airNo:false,
      bath0:false,
      bath1:false,
      bath2:false,
      bath3:false,
      bath4:false,
      balkony0:false,
      balkony1:false,
      balkony2:false,
      balkony3:false,
      balkony4:false,
      balkony5:false,
      furnitureYes:false,
      furnitureNo:false,
      kitchenYes:false,
      kitchenNo:false 
    },
    agreementValue: false,
  }

