export const CURRENCYSELECT = 'HEADER::CURRENCYSELECT';
export const LANGUAGESELECT = 'HEADER::LANGUAGESELECT';
export const PAGESELECT = 'HEADER::PAGESELECT';
export const PAGEPARAM = 'HEADER::PAGEPARAM';
export const DATABASE = 'DATABASE::FULLLOAD';
export const OBJECT = 'CARD::OBJECT';
export const SORTERVALUE = 'CARD::SORTERVALUE';
