export const CURRENCYSELECT = 'HEADER::CURRENCYSELECT';
export const LANGUAGESELECT = 'HEADER::LANGUAGESELECT';
export const PAGESELECT = 'HEADER::PAGESELECT';
export const PAGEPARAM = 'HEADER::PAGEPARAM';
export const DATABASE = 'DATABASE::FULLLOAD';
